name: 'GitHub Action for Perl Critic'
description: 'Run Perl Critic on your codebase.'
author: Difegue
branding:
  color: blue
  icon: eye
runs:
  using: docker
  image: Dockerfile
inputs:
  args:
    description: "Arguments to pass to perlcritic"
    required: false
